### ISSUE TITLE
Add ability to /jamute private group (in UI, can just be default when no group specified)

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/JukeAlert#12]
Also, it would be nice if you didn't have to retype this in every single session for every group.

**Comment by rourke750** [comment]
just do /jamute *

**Comment by GavJenks** [comment]
But I don't want to mute all my groups. I just want to have some super spammy groups muted until I want to listen to them. For example, snitches around rail entrances to my home town I always want to be on - nobody ever trips them more than once, and they are security critical. Whereas a snitch in the end is most of the time useless and SUPER spammy because people aimlessy run in circles. But during a key battle, it might be very important to know who was pearled by them showing up on end snitches and getting notifications.

**Comment by GavJenks** [comment]
Cool thanks (edited out other response, thought it was to another issue)

**Comment by rourke750** [comment]
So is this an issue?

**Comment by GavJenks** [comment]
Wait yes this is still an issue, I misunderstood. The asterisk just mutes EVERYTHING. I was looking for a way to mute ONLY the private group but not other groups. Have been trying it and just realized that it muted everything...

**Comment by GavJenks** [comment]
The private group does not have a groupname, so can't do that

But nevermind. Ttk's post on reddit clarified that citadel 3 is doing away with private group anyway, do that would make this moot.

**Comment by rourke750** [comment]
The private group name is your name?
