### ISSUE TITLE
Make /jamute persistent 

### ISSUE THREAD

**Issue by rourke750** [Civcraft/JukeAlert#15]

**Comment by jjj5311** [comment]
Do we want this to go into database, or seperate flat file?

**Comment by rourke750** [comment]
Keep in mysql.

**Comment by jjj5311** [comment]
okay, i am not real familiar with jukealert but will try to look into this tomorrow am

**Comment by jjj5311** [comment]
Okay i got it storing everything in the db, just having an issue with returning a set of UUID from sql?

When i run it for some reason it doesnt even seem to enter the try look for this method here

https://github.com/jjj5311/JukeAlert/blob/mute_persist/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1385-1406

I know the method is being called but it doesnt seem to be doing anything.. not sure if you have any ideas why that wouldnt work?

**Comment by rourke750** [comment]
what is the message fired.

**Comment by jjj5311** [comment]
Literally nothing, there is no exception, not set returned, and this line to leave the method is never fired either

https://github.com/jjj5311/JukeAlert/blob/mute_persist/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1404

this never went either

https://github.com/jjj5311/JukeAlert/blob/mute_persist/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1391

 i changed from SQLException to general exception to catch all 

I had a log in the first line of the method so i knew it was firing

**Comment by rourke750** [comment]
Use jd-gui and check that your code is actually there.  Or just try delete
and reexport it.

**Comment by erocs** [comment]
I've switched from jd-gui to https://github.com/Konloch/bytecode-viewer.

**Comment by jjj5311** [comment]
It shows that it's there and when I put the log back in the beginning it
shows up in console

**Comment by erocs** [comment]
BTW you have potential SQL injection.  https://github.com/jjj5311/JukeAlert/blob/mute_persist/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1387

**Comment by erocs** [comment]
Wait, you're using parameters, sorry. I should take more time looking at things.

**Comment by jjj5311** [comment]
Okay I am not too familiar with sql, what is correct wAy to do that to use

Select uuid from table where muted_groups like %likegroup(variable)%

**Comment by erocs** [comment]
Nah sorry, I didn't look close enough, you're fine as you're using parameterized SQL.

As for why this doesn't run, I don't know either. Is there any Exception whatsoever?

**Comment by jjj5311** [comment]
Nope nothing at all, with the initial logging line (not in the repo) it
prints that it entered the method and that's it

**Comment by erocs** [comment]
Try running the SQL statement directly in your SQL console and see if it works as expected.

**Comment by jjj5311** [comment]
I did try before and it worked cause when I had the sql wrong I got
exceptions

**Comment by jjj5311** [comment]
Okay I think I got it working now... will post the updates later

**Comment by jjj5311** [comment]
#17
