### ISSUE TITLE
Please put the snitch name in jalist's output.

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [Civcraft/JukeAlert#24]
It would help with working out where they are faster, without having to transfer the coordinates to a waypoint mod.

**Comment by ttk2** [comment]
I don't think this would be very difficult, is there a reason it was not
done before?

**Comment by ac7web** [comment]
Possibly screen-space being an issue in the chat window.

**Comment by Maxopoly** [comment]
This was added ages ago

**Comment by RailsDev42** [comment]
Please can you re-open? This hasn't been fixed. The only columns in jalist output are:

MC World, Location, Hours to cull and Group name.

Nowhere in that list do you print the name of the snitch, which would be a lot more user-friendly than a bunch of coordinates, when you have loads of them.

**Comment by Maxopoly** [comment]
Oh my bad, I read the title as /jainfo, yeah you are right.

**Comment by RailsDev42** [comment]
Thanks.

**Comment by Lcth** [comment]
Any chance of this getting added? Should be fairly easy to do I'd assume.

Relevant discussion on reddit: https://www.reddit.com/r/Civcraft/comments/493c73/changelog_20160305/d0owxpj

**Comment by waffle-stomper** [comment]
Would it be OK for me to move the world name from a column to a header line? As far as I can tell, you can only list snitches for the shard you're in, so the 'world' column values will always be the same. It would help free up room for longer group & snitch names.

**Comment by Maxopoly** [comment]
Seems fine to me
