### ISSUE TITLE
Truncation of long player names leads to unnecessary confusion

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/JukeAlert#25]
https://github.com/Civcraft/JukeAlert/blob/master/src/com/untamedears/JukeAlert/chat/SendSnitchInfo.java#L55

This line has caused me no end of problems, heh. The rationale for artificially limiting the displayed length of some of the most important information from the Juke logs has never sat well with me. I'm happy to address this one myself but figured I'd toss up an issue in case there was an actual legitimate reason.

**Comment by ProgrammerDan** [comment]
I lied; this is the offending line: https://github.com/Civcraft/JukeAlert/blob/master/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1192

**Comment by erocs** [comment]
It seems to make space for 20 chars. How is that truncating 16 char names?

**Comment by ProgrammerDan** [comment]
?? Player names are not limited to 16 characters. I routinely see people on snitches who names exceed the displayed value, and as a consequence their name is truncated. I am unable to appropriately pursue them in a bounty as I can't identify that it is indeed them.

**Comment by ProgrammerDan** [comment]
Or, are you suggesting that the database itself is hardcoded to only store 16 characters for each actor's name? That's ... well, that's terrible, if it's the case. I had assumed the 16 char DB field was for UNID, not translated actor name.

**Comment by rourke750** [comment]
A players name cannot exceed 16 characters is what he is saying.

**Comment by ProgrammerDan** [comment]
And I am saying that that is incorrect. I'll dig up some evidence in a bit.

**Comment by ProgrammerDan** [comment]
Alright, the name length may not be incorrect, but here's an example of the clipping in the client: 

http://imgur.com/Oysx6hA

The full name is EnderPearlHarbor, but the /jainfo command only displays EnderPearlHar.

This occurs regularly.

**Comment by erocs** [comment]
That's the group name.

**Comment by erocs** [comment]
No, no that's player name. It's something about whatever magic ChatFiller
is failing to do properly. Just remove ChatFiller.fillString from that line
you pointed out and I would think things would work.

**Comment by rourke750** [comment]
@erocs I think the fill line is so that each thing is for sure on one line.

**Comment by erocs** [comment]
But its truncating the name when it shouldn't.
