### ISSUE TITLE
Redstone pulse not triggering when snitch is triggered

### ISSUE THREAD

**Issue by Vastitas** [Civcraft/JukeAlert#27]
If a player who is not on the group of said snitch, when the snitch is triggered even while configured with /jatogglelevers 1, the snitch will not output a redstone signal from the lever, it will only trigger when said player places a block.  

Example:  http://i.imgur.com/umOlDbe.png

**Comment by rourke750** [comment]
Thx for making the issue. @BlackXnt @Xavter @ProgrammerDan Any of you want this otherwise I'll do it?

**Comment by ProgrammerDan** [comment]
Hmm, unless someone else thinks they can get to it tonight, toss it to me. It'll be my first P2, so I'll get on it starting this evening.

**Comment by erocs** [comment]
The snitch was sending the player enter notifications.

**Comment by erocs** [comment]
Also settings.allowTriggeringLevers is true in the config.

**Comment by BlackXnt** [comment]
Did you put the redstone in the north side of the snitch?

**Comment by rourke750** [comment]
So is this issue not necessary?

**Comment by BlackXnt** [comment]
yes you can close this.

**Comment by erocs** [comment]
Probably best if @Vastitas confirms this is the case.

**Comment by Vastitas** [comment]
Yeah it works, thanks guys
