### ISSUE TITLE
Add new Snitch type

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/JukeAlert#29]
Add a snitch that's a diamond block, identical in behavior to juke box but cuboid of 20 and it's own expiry time config option.

**Comment by rourke750** [comment]
@drjawa What do you think.  Going to assign you for discussion.

**Comment by drjawa** [comment]
What is the goal of this change?

**Comment by drjawa** [comment]
Not against but want to understand purpose.

**Comment by erocs** [comment]
Looks like only a larger snitch field. Is the current 11 block 'radius'
insufficient to hide the snitch from X-Ray with the current orebfuscator?

**Comment by drjawa** [comment]
Well currently snitches aren't being obfuscated at all due to oreobfuscator
being borked. Adding jukes and noteblocks to list does not with spigots ofc.

>_>

Maybe we should just convert snitches to be blocks that we can properly
obfuscate (Though that is the lazy and bad way out).

**Comment by ttk2** [comment]
either way why larger radius snitches? I guess lower matience at much higher cost, which I guess is reasonable, but even a factor of 9 is pretty affordable to some people. 

Does increase the theft chance though. 

Wait, how do we keep all placed diamond blocks from becoming snitches by default?

**Comment by Goldmattress** [comment]
The way we do the other blocks.

Its larger and nore expensive to make snitching large areas easier, at the
cist of less efficiency

**Comment by ttk2** [comment]
I can get the argument, what do you mean the same way we do for other blocks? The old crouch while you place thing?

**Comment by Goldmattress** [comment]
You really haven't played civcraft in a while have you.

Certain blocks when reinforced automatically become snitches on placement

**Comment by ttk2** [comment]
I am aware, but people use DIamond blocks in decorative purposes, or for beacons, should they just automatically make a beacon of snitches?

**Comment by ttk2** [comment]
That's a horrible solution. Crouch placing is probably the way to go.

**Comment by Goldmattress** [comment]
Please no, I fucking hated that in PS.

No one is complaining about the current system, it's completely fine we've
been doing it this way for 2+ years now.

**Comment by ProgrammerDan** [comment]
Could just have if you don't give it a name via /janame then it doesn't record / is inert.

**Comment by Goldmattress** [comment]
Nooo, I've forgotten to name thousands of snitches and I know a lot of
people never bother, just make a command so that when you break the block
it removes the snitch but keeps the block and reinforcement.

It is so much more common to be using these blocks in the context of JA
that it should be assumed that that is what the player is doing.

**Comment by ProgrammerDan** [comment]
I buy it. Can't think of the last time I used a Dblock as decoration.

**Comment by ttk2** [comment]
very well then, I agree on everything except maybe having members refresh them, if we can think of a better mechanic maybe we should do that. 

Having incentive to need to trust more people to help maintain such a network is very nice IHMO.

**Comment by Goldmattress** [comment]
Well if your set on that a longer time till cull should do the same in the
long run

**Comment by ttk2** [comment]
sounds good.

**Comment by Goldmattress** [comment]
Anyone have time to do this at some point?

**Comment by ttk2** [comment]
I don't think anyone sees this as a priority.

**Comment by Goldmattress** [comment]
No not at all, I'm just wondering before I write better documentation for JA.

**Comment by ttk2** [comment]
skip it for now.

**Comment by Maxopoly** [comment]
This feature is no longer desired and the general idea should rather be part of a refactor to allow more dynamic snitch configurations
