### ISSUE TITLE
Move snitch updating to members

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/JukeAlert#30]
Move snitch updating to members that can open chests on a citadel group.

**Comment by rourke750** [comment]
@ttk2 Thoughts?

**Comment by erocs** [comment]
We wanted that to be a cost. May as remove that aspect of snitch
maintenance if its changed to trigger on all members. (Not saying to do
that.  :P  )

**Comment by Goldmattress** [comment]
This is a balance change as is snitch protection is really weak and one of
the biggest things that allow raiders to go unscathed due to a lack of
evidence.

**Comment by ttk2** [comment]
If anyone in the group updates a snitch there is essentially no upkeep, that's going too far in the other direction IHMO, especially combined with the larger ones. 

Are snitches really that week at the moment? you just cant maintain huge networks.

**Comment by erocs** [comment]
Re: "raiders to go unscathed"  Bastions combined with snitches should be
providing protection and that shouldn't necessarily be a perfect defense.

**Comment by ttk2** [comment]
I can understand a desire to mitigate the need to walk your entire snitch network, but we need a replacement for that effort. 

The snitch powering factory was an interesting idea.

**Comment by drjawa** [comment]
I like the idea of the snitch power factory if any snitch can be added
to it + increased actual cost per snitch.

Of course cost balancing is always the worst....

**Comment by Goldmattress** [comment]
I ran the largest snitch network on the map with hundreds of mods and
maintaining vital parts from culling was hard.

Snitches form the basis of the justice system in civcraft and need to be
use able.

As it stands snitching buildings and large areas, especially large
buildings is damn hard. Complete coverage, the kind you need to prove grief
damage is harder still.

The way the system is atm it favours just placing thousands of dirt cheap
noteblocks to track locations.

Id like that kind of coverage to be extensive and for it to make sense to
refresh your snitches.

For this snitches need to be more expensive and cover large areas instead
of the pin point nature of noteblocks

Im rambling ill try and write up what I'd like the snitch system to be like

**Comment by Goldmattress** [comment]
Bastions do not protect against block breaks

**Comment by Goldmattress** [comment]
Basicslly i think snitches ate op at tracking and shite at their real aim,
logging

**Comment by ttk2** [comment]
OK. I see your argument. So nerf tracking and buff logging at higher costs.
Letting member refresh is a really big deal. It also kinda devalues the
importance placed on moderators by the previous system. Would longer
periods help?

**Comment by Goldmattress** [comment]
The problem is that you have to expose all of your snitches to immediate
tracking due to the /jalist command, anyone you give mod might as well be
an admin if it's a snitch group, you've surrendered any ability to protect
yourself at that point.

**Comment by ProgrammerDan** [comment]
I dunno what you had done to MN permissions, but MODS did not see snitch locations using /jalist.

**Comment by ttk2** [comment]
we can change the group permissions if that's a concession you will accept. 

But having to have people in a position of trust to help you out is a very good mechanic IHMO.

**Comment by Goldmattress** [comment]
I changed the premissions bc it eas easier than demoting hundreds of account

**Comment by ttk2** [comment]
so this mostly fixes an issue where the problem is you can't mass change perms?

**Comment by Goldmattress** [comment]
Yeah I think tackling this form Namelayer is better
