### ISSUE TITLE
Snitches can be re-named by members

### ISSUE THREAD

**Issue by erocs** [Civcraft/JukeAlert#41]
https://github.com/Civcraft/JukeAlert/blob/master/src/com/untamedears/JukeAlert/util/Utility.java#L78

JukeAlert should probably be enlightened with NameLayer permissions. If anything, this should probably be increased to moderators.

**Comment by Maxopoly** [comment]
Yeah just doing a complete namelayer integration would probably make sense, another issue right now is that anyone who is mod can run /jalist and get the location of every snitch, I remember someone having regex to even filter it by group.

**Comment by PatchyKnowly** [comment]
Bumping this as it's a pretty big problem with linking groups. Anyone who is a mod on a supergroup gets snitches from any linked subgroups with /jalist, as they're automatically a mod on the subgroup. If there were permissions for JANAME, JAINFO and JALIST, you could remove things you didn't want from the mods level of the subgroup.

Right now the solution is to give the 'blocks' permission to members in the supergroup and only put people you trust with full snitch locations as mods or higher, which is undesirable, as it constricts effective group management. As for the renaming, it would make sense for that to default to mods and not members.

**Comment by ProgrammerDan** [comment]
This can be solved soon, just fixing some other problems before merging in the custom permissions logic.

**Comment by Maxopoly** [comment]
Now tied to a permission with https://github.com/Civcraft/NameLayer/pull/191
