### ISSUE TITLE
Breaking snitches reveals who owns it?

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/JukeAlert#49]
I remember precious stones had this. I think it would be nice to  bring back, maybe only for not blocks to encourage the use of jukes if you want full anonymity?

@rourke750 @ttk2 thoughts?

**Comment by ttk2** [comment]
so the noteblock would report who owned it but a snitch would not? why not
just have both report who owns them?

**Comment by Maxopoly** [comment]
You could argue that the juke is a lot more expensive, but I think if we add this we should add it for both.

**Comment by TealNerd** [comment]
It could do that, I was just thinking since jukes are significantly more expensive it would be nice to give them that bonus. Plus jukes are typically used to snitch people's own stuff, whereas noteblocks are typically used to spam snitches in other people's stuff. It would either make it much easier for someone to check who's been snitching their stuff, or would force people to pay more for their networks.

That said if you think it should just be for all snitches that sounds good as well

**Comment by ttk2** [comment]
Jukes are more expensive, but that cost is for info storage, do we really
want to attach it to some other benefit? I think we should just do it for
all of them.

**Comment by TealNerd** [comment]
Yeah that's true. Ok I'll implement it with just a config options to turn it on or off

**Comment by rourke750** [comment]
So for this issue, you would need to store who reinforced a snitch not the group.  How would you go about implementing this for prexisting snitches?  

What approach do we want to take.  Owner of group would be easiest and would not require any db changes.  What were you thinking @TealNerd?

**Comment by Maxopoly** [comment]
The commit he added to the other PR a few days ago used the owner of the group: https://github.com/TealNerd/JukeAlert/commit/4fb8199b1181eabe5511028e5f9afe91db0bf7ed

I think additionally to the owner it should also show the name of the group, that would tell a lot.

**Comment by rourke750** [comment]
https://github.com/Civcraft/JukeAlert/pull/50
