### ISSUE TITLE
Idea: Horse mount & dismount tracking

### ISSUE THREAD

**Issue by walkersgaming** [Civcraft/JukeAlert#53]
Simple idea: add the ability to enable snitch logging of players mounting & dismounting horses. Useful for players trying to prove horse theft.

**Comment by ProgrammerDan** [comment]
Great suggestion, follows along with the minecart break tracking added a few months ago, for similar reasons.

**Comment by Maxopoly** [comment]
Ty for making the issue, I'll get to it at some point

**Comment by jjj5311** [comment]
I thought the cart logging was only for breaking of carts?

**Comment by Maxopoly** [comment]
Yeah it is

**Comment by ProgrammerDan** [comment]
@jjj5311 I mention it only b/c this would be a logical "next step" to follow on the cart break tracking. Cart breaking doesn't cover horse usage or mounting/dismounting entities in general.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/JukeAlert/commit/31f12b36958d1cbe74273f3151a0234d7e6f7995
