### ISSUE TITLE
JukeAlert SQLError

### ISSUE THREAD

**Issue by Rident** [Civcraft/JukeAlert#57]
After a couple hours, sometimes days, jukealert will sort of just implode on it's self and spew out this in the console: http://pastebin.com/F5BbSfbz

`28.02 00:01:24 [Server] INFO com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure`

`28.02 00:01:24 [Server] ERROR [JukeAlert] Could not get Snitch Details from the snitchesDetail table using the snitch id 14`

If I restart the server, the databases will return as normal, but otherwise it will just say," * Page 1 is empty for snitch Example".

**Comment by rourke750** [comment]
Looks like a just timing out issue.
@Civcraft/devs

**Comment by Rident** [comment]
@rourke750 
I'm guessing it would be a server side issue then?

**Comment by ProgrammerDan** [comment]
Configure your Mysql/Mariadb to have a longer connection timeout for now. It's not ideal. Set it to slightly longer then your server restart period.

**Comment by Rident** [comment]
@ProgrammerDan 

I'm not very proficient with MySQL or servers for that matter. If it's not too much to ask, could you direct me on how to configure that? because the directions I'm finding online are telling me to edit "my.cnf" in the /etc/ directory, but that file doesn't exist there. It does however in the /etc/mysql/ directory, but doesn't have anything detailing the max timeout time.

Supposedly I can also use Connector/J to set configure it to autoreconnect, but I'm unsure how that works either.

**Comment by ProgrammerDan** [comment]
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_wait_timeout

Add a line in section [mysqld] like this:

```
wait_timeout            = 27000
```

**Comment by ProgrammerDan** [comment]
Also it's on my todo to just add reconnect into JukeAlert, so hopefully in the next few days this won't be an issue any more :)

**Comment by Rident** [comment]
@ProgrammerDan 

Thank you, I appreciate it! and that'll definitely be useful. I've been pretty much pulling my hair out trying to fix this for a bit now aha. I thought maybe I had setup the database wrong or something.

**Comment by ProgrammerDan** [comment]
I hear ya. First few times I ran into it I had the same thoughts!

**Comment by Maxopoly** [comment]
This is the same issue we are having currently.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/JukeAlert/commit/a71921c3fb5bcae299c11ba114fb80b7940a496b
