### ISSUE TITLE
Combatloggers show up on snitches

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/JukeAlert#64]
Sometimes there are even snitches that just show an entry of a combatlogger.

**Comment by ProgrammerDan** [comment]
Are we using random-name combat loggers? Can you paste an imgur or other example? 

I'm not clear what the issue is, here.

**Comment by Maxopoly** [comment]
http://puu.sh/nZDtk/965e8de6de.png

The guy wanted to know who visited his bunker. No idea how that even happened.

**Comment by ProgrammerDan** [comment]
Hmm, check CTP settings on the shard; might be a rogue "use random combatlogger" setting.

**Comment by Crushtoe** [comment]
Can confirm that combatloggers 'logging in' has been popping up on snitches for at least a few days now in Gimmel.

**Comment by Maxopoly** [comment]
Yeah, some configs had it enabled. I updated all of them to not generate random loggers.
