### ISSUE TITLE
Again, this is the JukeAlert repository.  Not Janitor.  We can't help you with plugins we don't have any connection to. If you get an error message that says "Can't pass event to JukeAlert" -- post it here, otherwise, we can't help you.

### ISSUE THREAD

**Issue by Aivaruxx** [Civcraft/JukeAlert#85]
Where? Where can i post it then!?

**Comment by ProgrammerDan** [comment]
Where did you download Janitor from? Find that repository, usually on Bukkitdev or SpigotMC. Unfortunately, posting a stacktrace to a random repository isn't going to get you anywhere.
